import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/utils/Header";

const rubik = localFont({
  src: [
    {
      path: "../public/fonts/Rubik-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/Rubik-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Rubik-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/Rubik-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-rubik",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${rubik.variable} antialiased bg-primary`}
      >
        <div className="w-full h-screen flex flex-col">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
